### ISSUE TITLE
这是否有点

### ISSUE THREAD

**Issue by Cuthead** [spartacus-soft/spartacus#4]
从[彭先生论坛](https://archive.is/qrzpK)来的。

@toorich @lifegpc

来看看这位的“完全自研”。

Wikipedia 的 91.198 的 IP 几个月前就被 WMF 替换了。（更新：也不是几个月前，而是[整一年前](https://zh.wikipedia.org/w/index.php?title=Help:如何访问维基百科&diff=prev&oldid=78608330)，这位先生图利心切在抄配置之前甚至不愿意 ping 一下连通性）

api.twitter 我 [2 年前扫描出来](https://repo.or.cz/gscan_quic.git/commitdiff/300f445f7f5961297f85d83c849905d7990d1e6b)的放里面存档，现在大多数都不能用了。

googlevideo 的一堆 IP 不知道从哪来的，sn 对不上就不会有内容。

- https://repo.or.cz/gscan_quic.git
- https://repo.or.cz/Accesser.git
- https://github.com/macronut/phantomsocks
- https://github.com/WhiteCutey/TCPioneer-Hmoegirl

👆是不是看到上面开源项目的配置文件里有就觉得可以直连就抄来用👆

还拿出来卖钱，笑死人了。

@macronut 我很怀疑这位用了 phantomsocks ，不知是否违反 LGPL 。

**Comment by spartacus-soft** [comment]
@Cuthead 笑死，你可以不懂，可以怀疑，但别指鹿为马，只会体现无知

**Comment by spartacus-soft** [comment]
settings是给用户自忆改的内容，有问题吗？
选择是否闭源，也不需要向你解释吧

**Comment by spartacus-soft** [comment]
> @ValdikSS Can you imagine some 'people' packaged GoodbydDPI and reband it a proprietary subscription product and profit from it?
但凡会写`hello world`的人，都觉得这个断言是多么无知。

**Comment by spartacus-soft** [comment]
姑且假设你了解LGPL，当你怀疑之后，你好歹分析PE结构、反编译查找函数、汇编指令等特征吧。
但貌似你只凭着意念各种意淫可笑的无知结论呢

**Comment by spartacus-soft** [comment]
你信与不信，不是我要处理的事情，而是你需要对自己的怀疑进行分析。如果不幸你现在不会分析，可以多学习呢。
另外，e=mc*c，不等于所有原子弹都是一个模具里出来的；还有你不会以为拿了别人的原子弹包上一些炸药威力就翻N倍吧。

**Comment by spartacus-soft** [comment]
hosts.txt格式或内容侵犯了什么协议了吗

**Comment by spartacus-soft** [comment]
你还想需要我帮你无偿分析其它吗？我想`你应该不是一个到处怀疑他人，却臆想着让他人自证的人吧`？

**Comment by spartacus-soft** [comment]
在你增加更多的质疑来逃避你之前论断之前，请你先把你先处理你之前各种不过脑的论断吧。

**Comment by spartacus-soft** [comment]
> 直接复制粘贴某处的 hosts 没任何处理，不考虑其中的记录是否仍有效。一个30天试用的专有订阅制产品是否应当依赖复制粘贴来的东西才能确保工作呢？
> 
> > 直连访问除IP封锁之外的所有服务
> 
> > [试试直连工具，这样就是你的真实的干净IP](https://archive.is/qrzpK)
> 
> 比如这位要访问的，是IP封锁吧？而您很明显没有对此作好准备。却急着盈利了。

这里你更搞笑了，你对你要喷的产品都不了解，就得结论了。你是没看到`应用模式`里有两个选项吧。

**Comment by spartacus-soft** [comment]
那你慢慢寻思吧，多想想直连时，干净IP的IP两字，是否等于客户端公网IP，想通你拍大腿也行。
还有，此issues无任何营养。
